### ISSUE TITLE
Master branch not sync. with 4.0.0

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/manifest#250]
Hello 
It seems that `master` branch hasn't been synchronized to version 4.0.0

![image](https://github.com/OP-TEE/manifest/assets/43228610/26c4e07a-cf96-4451-aa29-dab9a0ab4b2c)

**Comment by jforissier** [comment]
Hello,

It is expected. The manifest file in the master branch points to the latest `optee_*` code (it has `revision="master"`). When a new release is tagged, the manifest is modified to make the subprojects point to that tag instead (`revision="refs/tags/4.0.0"`), so it is one commit ahead (the [commit](https://github.com/OP-TEE/manifest/commit/e20220b5bd1fbc49df675361cb3fbfa7820e67af) that changes `"master"` to `"refs/tags/4.0.0"`). The master branch is left untouched because we still want it to track master.

**Comment by gagachang** [comment]
Oh! I didn't realize it. Thanks for explanation.
