### ISSUE TITLE
Not able to fetch firmware project for raspberrypi 3 platform

### ISSUE THREAD

**Issue by nutim** [OP-TEE/manifest#88]
I am using procedure to install optee on raspberrypi 3 as given in [optee website](https://www.op-tee.org/build/) 

But while `repo sync` i am getting error 

`Fetching projects:  41% (5/12)  Fetching project firmware.git
error: no such remote ref 3fb63c413cabfddb7fb9ed286bfc62abe73cc310
error: Cannot fetch firmware.git
error: Exited sync due to fetch errors` 

is there any change in remote revision id?

**Comment by igoropaniuk** [comment]
Hi @nutim,
Seems that when `rpi3_stable.xml`(I guess you are trying to use this one) was created, tag  `refs/tags/1.20170215` was replaced with sha hash `3fb63c413cabfddb7fb9ed286bfc62abe73cc310`. Unfortunately it can't be used mutually with ` clone-depth="1"`. Although, since Git version 2.5 servers may expose raw hashes, most server administrators disable this feature (it's server-side configuration item) because of security flaws.

Try to use `rpi3.xml` instead. BTW, I've just tested it - it works perfectly:
```
rpi3$ repo init -u https://github.com/OP-TEE/manifest.git -m rpi3.xml && repo sync -j20
rpi3$ cd firmware/
rpi3$ git log
commit 3fb63c413cabfddb7fb9ed286bfc62abe73cc310
Author: popcornmix <popcornmix@gmail.com>
Date:   Wed Feb 15 17:21:16 2017 +0000

    firmware: FXL6408/GPIOman: Support config of termination via dt-blob
    firmware: GPIO expander: Add API to reconfigure pins
    firmware: GPIOMAN: Add API to reconfigure pins
    firmware: Mailbox service: Add command to reconfigure GPIO setup
    firmware: FXL6408: Return success code on reading status of an output
    firmware: GPIO expander: Add set/get_config functions to dummy driver
```
BR,
Igor

**Comment by jforissier** [comment]
@igoropaniuk would you mind creating a PR to replace the SHA1 with the tag reference? Thanks.

**Comment by igoropaniuk** [comment]
Hi @jforissier,

Done https://github.com/OP-TEE/manifest/pull/89

**Comment by nutim** [comment]
Hi @igoropaniuk , 

Thanks vert much for quick response. I am able to download and build everything on my Pi. Let me know if I should close the issue or we need to wait for any other procedure. Thanks

Regards,
Mallik
